### ISSUE TITLE
Express more accurately the real mapConserve behavior

### ISSUE THREAD

**Issue by superruzafa** [superruzafa/visual-scala-reference#12]
The [`mapConserve` page](https://superruzafa.github.io/visual-scala-reference/mapConserve) is not expressing accurately the real behavior of that function, neither in the description nor the diagram, as shown in #8

**Comment by superruzafa** [comment]
@exoego, I just pushed a branch named `fix-mapconserve` (8dfd46b) to fix this issue.
Feel free to checkout it to review and update the japanese translation for that function. You can create a PR then if you wish.

**Comment by exoego** [comment]
> 
> 
> @exoego, I just pushed a branch named `fix-mapconserve` ([8dfd46b](https://github.com/superruzafa/visual-scala-reference/commit/8dfd46b5d9489a4737b7ab189180bb5b54940c1c)) to fix this issue.
> Feel free to checkout it to review and update the japanese translation for that function. You can create a PR then if you wish.

LGTM 👍 
I will create a PR within this week.
