### ISSUE TITLE
Inconsistent use of Seq instead of Collection 

### ISSUE THREAD

**Issue by exoego** [superruzafa/visual-scala-reference#7]
The below 2 pages uses type `Seq` instead of `Collection`.
https://superruzafa.github.io/visual-scala-reference/isDefinedAt_Seq
https://superruzafa.github.io/visual-scala-reference/isDefinedAt_Map

Is this intended? If so, I would like to know why.
If not intended, it should be corrected.

**Comment by superruzafa** [comment]
It's intended in the sense that I`isDefinedAt` is defined only for `Seq` and `Map` but not `Set`.
Anyway there is a typo in the documentation where `Seq` is duplicated in the two documents that I'll fix.
